// catches the asynchronous and synchronous errors
// for login logout registers, accept those functions
export const catchAsyncErrors = (theFunction) => {
    return (req, res, next) => {
      Promise.resolve(theFunction(req, res, next)).catch(next);
    };
  };